peer:
  id: peer1-logistics1
  networkId: dev
  address: 0.0.0.0:7051
  localMspId: Logistics1MSP
  
  BCCSP:
    Default: SW
    SW:
      Hash: SHA2
      Security: 256
      FileKeyStore:
        KeyStore: /etc/hyperledger/msp/keystore

